# yaml-language-server: $schema=../../core/target/classes/com/predic8/membrane/core/config/json/membrane.schema.json
#
# Membrane Tutorial: OpenAPI Validation
#
# 1) Try creating a new product with a negative price:
#
#      curl "http://localhost:2000/shop/v2/products" -H 'Content-Type: application/json' -d '{ "name": "Figs", "price": -2.7}'
#
#    Check the validation error in the response.

spec:
  port: 2000
  specs:
    - openapi:
        location: ../../conf/fruitshop-api.yml
        validateRequests: true
        validateResponses: true
        validationDetails: true