# yaml-language-server: $schema=https://www.membrane-api.io/v7.1.0.json
#
# Tutorial: OpenAPI Validation
#
# Try creating a new product with a negative price:
#    curl "http://localhost:2000/shop/v2/products" -H 'Content-Type: application/json' -d '{ "name": "Figs", "price": -2.7}'
#
#    Check the validation error in the response.

api:
  port: 2000
  openapi:
    - location: ../../conf/openapi/fruitshop-v2-2-0.oas.yml
      validateRequests: true
      validateResponses: true
      validationDetails: true
