
# yaml-language-server: $schema=https://www.membrane-api.io/v7.0.0.json
api:
  port: 2000
  specs:
    - openapi:
        location: "https://api.predic8.de/shop/v2/api-docs"

---

api:
  port: 2000
  target:
    url: "https://api.predic8.de"