# yaml-language-server: $schema=https://www.membrane-api.io/v7.1.0.json
#
# Tutorial: Central TLS Configuration
#
# Try:
#     curl https://localhost:8443/foo -k
#     curl https://localhost:8443/bar -k

components:
  myssl:
    ssl:
      key:
        private:
          location: membrane-key.pem
        certificates:
          - location: membrane.pem

---
api:
  $ref: "#/components/myssl"
  path:
    uri: /foo
  port: 8443
  flow:
    - static:
        src: Foo
    - return:
        status: 200

---
api:
  $ref: "#/components/myssl"
  path:
    uri: /bar
  port: 8443
  flow:
    - static:
        src: Bar
    - return:
        status: 200
